### ISSUE TITLE
Did this get patched? Date History not working

### ISSUE THREAD

**Issue by BenjaminHCCarr** [Shpota/github-activity-generator#12]
Did this get patched, the script appears to work
```
[main a117ef6] "Contribution: 2020-11-28 20:06"
 Date: Sat Nov 28 20:06:18 2020 -0500
 1 file changed, 2 insertions(+)
[main 5245bfc] "Contribution: 2020-12-01 20:00"
 Date: Tue Dec 1 20:00:18 2020 -0500
 1 file changed, 2 insertions(+)
[main dcf0bc1] "Contribution: 2020-12-01 20:01"
 Date: Tue Dec 1 20:01:18 2020 -0500
 1 file changed, 2 insertions(+)
[main 3ec99da] "Contribution: 2020-12-01 20:02"
 Date: Tue Dec 1 20:02:18 2020 -0500
 1 file changed, 2 insertions(+)
Enumerating objects: 4704, done.
Counting objects: 100% (4704/4704), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3135/3135), done.
Writing objects: 100% (4704/4704), 429.40 KiB | 874.00 KiB/s, done.
Total 4704 (delta 1552), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1552/1552), done.
To github.com:BenjaminHCCarr/testing_repo.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.

Repository generation completed successfully!
```

But then I don't see the activity graph populated and the git history itself only shows today:

![image](https://user-images.githubusercontent.com/8225968/101085674-c65b7a00-357d-11eb-9b88-4f6b40b58f0a.png)

**Comment by Shpota** [comment]
What is the output of `git log` in the repository?

**Comment by BenjaminHCCarr** [comment]
looks correct:
```
commit 3ec99da3cb0b96d289000883c8075248c0c5930c (HEAD -> main, origin/main)
Author: Benjamin Carr, PhD <ben.carr@REDACT>
Date:   Tue Dec 1 20:02:18 2020 -0500

    "Contribution: 2020-12-01 20:02"

commit dcf0bc10c6d164af41c8f57913e90a364b6c9782
Author: Benjamin Carr, PhD <ben.carr@REDACT>
Date:   Tue Dec 1 20:01:18 2020 -0500

    "Contribution: 2020-12-01 20:01"

commit 5245bfc44b830a23330cdde1ab0d40453ea1aa72
Author: Benjamin Carr, PhD <ben.carr@REDACT>
Date:   Tue Dec 1 20:00:18 2020 -0500

    "Contribution: 2020-12-01 20:00"

commit a117ef61a9821d8c509b14e480c73085a76a4e44
Author: Benjamin Carr, PhD <ben.carr@REDACT>
Date:   Sat Nov 28 20:06:18 2020 -0500

    "Contribution: 2020-11-28 20:06"
```

**Comment by emanuelbaltaretu** [comment]
I am having the same issue, git log contribution looks correct but i get the same result as BenjaminHCCarr

**Comment by Shpota** [comment]
@emanuelbaltaretu have you checked the [troubleshooting section](https://github.com/Shpota/github-activity-generator#still-no-luck)? The issue is most likely in the email address you use for commits. It has to be the same as you have in your GitHub account.

**Comment by emanuelbaltaretu** [comment]
Thank you @Shpota !!! I did checked the troubleshooting section but git config --get user.email was returning "emanuel.baltaretu@gmail.com" i didn't see it at first but the dot was caussing the issue and it the script worked for me after changing it, thanks a lot!

**Comment by wasid** [comment]
Will it work on GitLab? I am testing it just for fun on my GitLab account and faced the same issue like @BenjaminHCCarr. It commits accurately but without any activity graph. However, it worked perfectly on GitHub. I am using the same email and others for both accounts.

**Comment by Shpota** [comment]
@wasid might be your profile is setup to hide private contributions

**Comment by wasid** [comment]
> @wasid might be your profile is setup to hide private contributions

@Shpota not exactly, it's open to all for private project activity graph, and I can see the profile in incognito: https://gitlab.com/wasid
