### ISSUE TITLE
Add a CI step that executes the script

### ISSUE THREAD

**Issue by Shpota** [Shpota/github-activity-generator#14]
A new CI step has to be added that will:
- perform the script passing all the parameters except the repository (it doesn't have to push the changes)
- verifies that the script generates a git repository and that there are commits

**Comment by danieldeer** [comment]
Hi, I like this project and would like to contribute. Can you elaborate this issue a little? What does "CI" stand for?

What do you mean with "perform the script passing all the parameters except the repository (it doesn't have to push the changes)" The script already parses all the parameters?

The second step "verifies that the script generates a git repository and that there are commits" is clear to me.

**Comment by Shpota** [comment]
Hi @danieldeer !

CI stands for [continuous integration](https://docs.github.com/en/actions/guides/about-continuous-integration) which is configured vi GitHub Actions in this repository. You can check the configuration [here](https://github.com/Shpota/github-activity-generator/blob/master/.github/workflows/build.yml). At the moment, it only compiles the script and checks formatting. The idea is that, on every push/pull request, the CI should also execute the script in order to verify that it actually works. It doesn't have to push changes because it would be complex to simulate as there has to be a repo to push to. But juts generating commits would be a good step forward.

Let me know if this helps.
