### ISSUE TITLE
No visible effect on the contribution chart

### ISSUE THREAD

**Issue by IshanJ25** [Shpota/github-activity-generator#20]
It has been ~30 mins since I ran the script, but there is no visible effect on the chart at my GitHub profile. However, the contribution count has changed as expected, but no change in graph. I have "Show private contributions" option turned on.

I have 2 questions:
  - does this still work?
  - how long it takes to come in effect?

**Comment by Shpota** [comment]
Have you checked [the troubleshooting section](https://github.com/Shpota/github-activity-generator#troubleshooting)?

**Comment by IshanJ25** [comment]
sorry i didnt check that earlier. resetting the email worked.
