### ISSUE TITLE
Error with the Query 

### ISSUE THREAD

**Issue by ChintzRuparel** [Shpota/github-activity-generator#21]
Hey, 

Can anyone please explain me the query to initialise the code?

```python contribute.py --repository=git@github.com:user/repo.git```

Please provide me with an example. 

Thanks and Regards, 
Chintan Nirmal Ruparel 
@ChintzRuparel

**Comment by Shpota** [comment]
Here is an excample:

```
python contribute.py --repository=git@github.com:ChintzRuparel/name-of-yout-repo.git
```

**Comment by ChintzRuparel** [comment]
Hey @Shpota, 

I will try with a similar query and get back to you!

Thanks and Regards, 
@ChintzRuparel
