### ISSUE TITLE
Unable to specify date range

### ISSUE THREAD

**Issue by HashCookie** [Shpota/github-activity-generator#28]
For example： I want April 1, 2015 to October 1, 2015 but it will go past October 1, 2015 without stopping and I set --days_before= and --days_after=0,I just want a specific period of time.

**Comment by 0vm** [comment]
you just need to get the days from and before, also, you have to remove the part where days before being under 0 is not allowed, and set it to be - days after, eg, days before is 99 and days after needs to be -60, that would be 3 months ago only
