### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by vishantbhole** [Shpota/github-activity-generator#48]
I created new repo public/private, did not initialized it 
I am getting below error.

error: unknown switch `b'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

**Comment by ChristiaanPrinsloo** [comment]
too bad

**Comment by Shpota** [comment]
Please share more details. What error do you get? What OS are you running? What version of Python do you have? What exactly did you run?

**Comment by vishantbhole** [comment]
I am using Mac OS 13.7, i tried with both python 2.7.16 and python 3.13.0
command i used is
python3 contribute.py --max_commits=12 --frequency=60 --repository=git@github.com:vishantbhole/project.git

**Comment by vishantbhole** [comment]
Is there any way we can delete this issue?
its showing on my profile
