### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cherisn** [Shpota/github-activity-generator#57]
The workflow is not running and throwing an error stating an empty line is found in contribute.py

**Comment by cherisn** [comment]
<img width="1448" alt="Screenshot 2024-11-08 at 17 04 40" src="https://github.com/user-attachments/assets/84acad01-44e0-45e0-b116-2c89461428cf">

This showed that the code is executed, but I don't find any changes in my GitHub contributions graph

**Comment by Shpota** [comment]
Follow the instructions [from the readme](https://github.com/Shpota/github-activity-generator?tab=readme-ov-file#how-to-use).
