### ISSUE TITLE
Error :Permission denied (publickey).

### ISSUE THREAD

**Issue by code-with-raiden** [Shpota/github-activity-generator#60]
1 file changed, 2 insertions(+)
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Repository generation completed successfully!

**Comment by Sarthak-code360** [comment]
Delete everything created and Create a new SSH key and verify it then,
Re-run the command.

**Comment by code-with-raiden** [comment]
bruh how to create a new ssh key can u give me a step by step guide

**Comment by Sarthak-code360** [comment]
1. Generate a New SSH Key
Open your terminal and run:
```
ssh-keygen -t ed25519 -C "your_email@example.com"
```
Replace "your_email@example.com" with the email you use for Git.
When prompted, press Enter to save the key in the default location.
You can also set a passphrase (optional) for extra security.

2. Add the SSH Key to Your SSH Agent
Start the SSH agent:
```
eval "$(ssh-agent -s)"
```
Add your new SSH key:
```
ssh-add ~/.ssh/id_ed25519
```
3. Copy Your SSH Key
Copy the SSH key to your clipboard:
```
cat ~/.ssh/id_ed25519.pub
```
Then copy the key manually or use a clipboard tool (like pbcopy on macOS).

4. Add the SSH Key to Your Git Account
Go to GitHub/GitLab/Bitbucket > Settings > SSH and GPG Keys.
Click New SSH Key, paste your key, and save.

5. Test Your SSH Connection
Run this command to verify:
```
ssh -T git@github.com
```
Replace github.com with your Git provider if using GitLab or Bitbucket.
If successful, you’ll see a message like:
"Hi username! You've successfully authenticated..."

**Comment by Shramkoweb** [comment]
> bruh how to create a new ssh key can u give me a step by step guide

[How to create SHH keys](https://shramko.dev/blog/how-to-create-ssh-keys)

**Comment by code-with-raiden** [comment]
thanks dude ill check it be in contact

**Comment by Zkh-dot** [comment]
> 1 file changed, 2 insertions(+) [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.
> 
> Repository generation completed successfully!

if you don't want to re-create your ssh key you can check read rights to it by ls -la ~/.ssh
if you want a step by step guide how to do it please provide outputs from commands
`whoami`
`ls -la ~/.ssh`

**Comment by Atteq786** [comment]
Tried out these steps but the issue is still same.
