### ISSUE TITLE
as  a  noob  i didnt not know how to use git and github that's whaen this kind of error happen

### ISSUE THREAD

**Issue by shivpatil** [Shpota/github-activity-generator#7]
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

the above happens at the end

**Comment by Shpota** [comment]
This message means that your computer does not have access to your GitHub account.

You can solve this in two ways:
1. You can configure an SSH access following [this guide](https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) and then run the script like this:
```
python contribute.py --repository=git@github.com:user/repo.git
```
2. Or alternatively you might want to use HTTPS. You can find the HTTPS link in the Clone dialog in your GitHub repository, look for 'Use HTTPS' option):
```
python contribute.py --repository=https://github.com/user/repo.git
``` 
In this way Git will ask you to authenticate with your GitHub account, but SSH keys won't be needed.

You can also read the [Troubleshooting](https://github.com/Shpota/github-activity-generator#troubleshooting) section.

let me know if this helped.

**Comment by shivpatil** [comment]
Thank you brodha over internet
